name: ArkLobby
version: '${project.version}'
main: fr.skytryx.arklobby.ArkLobby
api-version: 1.20
commands:
  build:
    permission: lobby.build.use
    description: Toggle build mode
    usage: "§3Usage: /build"
  register:
    description: Register your account
    usage: "§3Usage: /register <password> <password>"
  login:
    description: Login to your account
    usage: "§3Usage: /login <password>"
  unregister:
    description: Unregister a player from the server
    usage: "§3Usage: /unregister <ign>"
    permission: lobby.unregister.use
  whitelist:
    description: Adds/removes a player from the whitelist
    usage: "§3Usage: /whitelist <ign>"
    permission: lobby.whitelist.use