name: PigmanLobby
version: '${project.version}'
main: fr.skytryx.pigmanlobby.PigmanLobby
api-version: 1.20
commands:
  build:
    permission: lobby.build.use
    description: Toggle build mode
    usage: "ยง3Usage: /build"
  register:
    description: Register your account
    usage: "ยง3Usage: /register <password> <password>"
  login:
    description: Login to your account
    usage: "ยง3Usage: /login <password>"
  unregister:
    description: Unregister a player from the server
    usage: "ยง3Usage: /unregister <ign>"
    permission: lobby.unregister.use